### ISSUE TITLE
No case clause matching []

### ISSUE THREAD

**Issue by alex88** [sger/elixir_dropbox#3]
With this code:

```
def run() do
  client = ElixirDropbox.Client.new("xxx")
  ElixirDropbox.Users.current_account_to_struct(client) |> IO.inspect
  ElixirDropbox.Files.ListFolder.list_folder(client, "/data")
end
```

I get:

```
** (CaseClauseError) no case clause matching: []
    (hackney) xxx/deps/hackney/src/hackney_url.erl:192: :hackney_url.parse_netloc/2
    (hackney) xxx/deps/hackney/src/hackney.erl:331: :hackney.request/5
    (httpoison) lib/httpoison/base.ex:439: HTTPoison.Base.request/9
    (httpoison) lib/httpoison.ex:66: HTTPoison.request!/5
    (elixir_dropbox) lib/elixir_dropbox.ex:44: ElixirDropbox.post_request/4
    (elixir_dropbox) lib/users.ex:51: ElixirDropbox.Users.current_account_to_struct/1
    (uploader) lib/uploader.ex:6: Uploader.run/0
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
```

**Comment by ScrimpyCat** [comment]
I'm getting the same error. Many functions will raise that exception while some others like file download raise a non-existent domain error (`:nxdomain`). 

Was there some fix for this or is the project itself just not working properly?

**Comment by bsbodden** [comment]
This and many libraries using HTTPoison seem to be broken with Elixir > 1.8.1
```
Interactive Elixir (1.8.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> client = ElixirDropbox.Client.new("xxxxx")
%ElixirDropbox.Client{
  access_token: "xxxxxxxx"
}
iex(2)> ElixirDropbox.Users.current_account(client)
** (CaseClauseError) no case clause matching: []
    (hackney) /Users/bsb/Documents/Code/clients/pragprog/cloud_distributor/deps/hackney/src/hackney_url.erl:211: :hackney_url.parse_netloc/2
    (hackney) /Users/bsb/Documents/Code/clients/pragprog/cloud_distributor/deps/hackney/src/hackney.erl:345: :hackney.request/5
    (httpoison) lib/httpoison/base.ex:439: HTTPoison.Base.request/9
    (httpoison) lib/httpoison.ex:66: HTTPoison.request!/5
    (elixir_dropbox) lib/elixir_dropbox.ex:44: ElixirDropbox.post_request/4
iex(2)>
```

**Comment by ludwikbukowski** [comment]
the same issue here
